apiVersion: v1
kind: Service

metadata:
  name: monitoring-service
  namespace: monitoring

spec:
  selector:
    app: pod-monitoring

  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090